In [1]:
import sys
sys.path.insert(0, '/10 A KAI 2/Week 2/EDA_TellCo/')

In [2]:
from scripts.Basic_info import EDA
from scripts.db_conn import DataLoader

In [3]:
load = DataLoader()

In [4]:
df = load.fetch_data()

d:\10 A KAI 2/Week 2/EDA_TellCo\scripts\db_conn.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.conn)

In [5]:
res = EDA(df)

In [6]:
res.missing_values()

Bearer Id                                      991
Start                                            1
Start ms                                         1
End                                              1
End ms                                           1
Dur. (ms)                                        1
IMSI                                           570
MSISDN/Number                                 1066
IMEI                                           572
Last Location Name                            1153
Avg RTT DL (ms)                              27829
Avg RTT UL (ms)                              27812
Avg Bearer TP DL (kbps)                          1
Avg Bearer TP UL (kbps)                          1
TCP DL Retrans. Vol (Bytes)                  88146
TCP UL Retrans. Vol (Bytes)                  96649
DL TP < 50 Kbps (%)                            754
50 Kbps < DL TP < 250 Kbps (%)                 754
250 Kbps < DL TP < 1 Mbps (%)                  754
DL TP > 1 Mbps (%)                             754
UL TP < 10 Kbps (%)                            792
10 Kbps < UL TP < 50 Kbps (%)                  792
50 Kbps < UL TP < 300 Kbps (%)                 792
UL TP > 300 Kbps (%)                           792
HTTP DL (Bytes)                              81474
HTTP UL (Bytes)                              81810
Activity Duration DL (ms)                        1
Activity Duration UL (ms)                        1
Dur. (ms).1                                      1
Handset Manufacturer                           572
Handset Type                                   572
Nb of sec with 125000B < Vol DL              97538
Nb of sec with 1250B < Vol UL < 6250B        92894
Nb of sec with 31250B < Vol DL < 125000B     93586
Nb of sec with 37500B < Vol UL              130254
Nb of sec with 6250B < Vol DL < 31250B       88317
Nb of sec with 6250B < Vol UL < 37500B      111843
Nb of sec with Vol DL < 6250B                  755
Nb of sec with Vol UL < 1250B                  793
Social Media DL (Bytes)                          0
Social Media UL (Bytes)                          0
Google DL (Bytes)                                0
Google UL (Bytes)                                0
Email DL (Bytes)                                 0
Email UL (Bytes)                                 0
Youtube DL (Bytes)                               0
Youtube UL (Bytes)                               0
Netflix DL (Bytes)                               0
Netflix UL (Bytes)                               0
Gaming DL (Bytes)                                0
Gaming UL (Bytes)                                0
Other DL (Bytes)                                 0
Other UL (Bytes)                                 0
Total UL (Bytes)                                 1
Total DL (Bytes)                                 1
dtype: int64

In [7]:
res.data_types()

Bearer Id                                   float64
Start                                        object
Start ms                                    float64
End                                          object
End ms                                      float64
Dur. (ms)                                   float64
IMSI                                        float64
MSISDN/Number                               float64
IMEI                                        float64
Last Location Name                           object
Avg RTT DL (ms)                             float64
Avg RTT UL (ms)                             float64
Avg Bearer TP DL (kbps)                     float64
Avg Bearer TP UL (kbps)                     float64
TCP DL Retrans. Vol (Bytes)                 float64
TCP UL Retrans. Vol (Bytes)                 float64
DL TP < 50 Kbps (%)                         float64
50 Kbps < DL TP < 250 Kbps (%)              float64
250 Kbps < DL TP < 1 Mbps (%)               float64
DL TP > 1 Mbps (%)                          float64
UL TP < 10 Kbps (%)                         float64
10 Kbps < UL TP < 50 Kbps (%)               float64
50 Kbps < UL TP < 300 Kbps (%)              float64
UL TP > 300 Kbps (%)                        float64
HTTP DL (Bytes)                             float64
HTTP UL (Bytes)                             float64
Activity Duration DL (ms)                   float64
Activity Duration UL (ms)                   float64
Dur. (ms).1                                 float64
Handset Manufacturer                         object
Handset Type                                 object
Nb of sec with 125000B < Vol DL             float64
Nb of sec with 1250B < Vol UL < 6250B       float64
Nb of sec with 31250B < Vol DL < 125000B    float64
Nb of sec with 37500B < Vol UL              float64
Nb of sec with 6250B < Vol DL < 31250B      float64
Nb of sec with 6250B < Vol UL < 37500B      float64
Nb of sec with Vol DL < 6250B               float64
Nb of sec with Vol UL < 1250B               float64
Social Media DL (Bytes)                     float64
Social Media UL (Bytes)                     float64
Google DL (Bytes)                           float64
Google UL (Bytes)                           float64
Email DL (Bytes)                            float64
Email UL (Bytes)                            float64
Youtube DL (Bytes)                          float64
Youtube UL (Bytes)                          float64
Netflix DL (Bytes)                          float64
Netflix UL (Bytes)                          float64
Gaming DL (Bytes)                           float64
Gaming UL (Bytes)                           float64
Other DL (Bytes)                            float64
Other UL (Bytes)                            float64
Total UL (Bytes)                            float64
Total DL (Bytes)                            float64
dtype: object

In [8]:
df

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,D20434A,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,D10223C,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,T51102A,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,L88342B,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,None,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [9]:
res.remove_columns()

Warning: The following columns were not found and will not be dropped: ['17  Nb of sec with 31250B < Vol DL < 125000B', '18  Nb of sec with 37500B < Vol UL', '15  Nb of sec with 125000B < Vol DL', '16  Nb of sec with 1250B < Vol UL < 6250B']

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,HTTP UL (Bytes),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,NaN,...,1.585461e+07,2.501332e+06,8.198936e+06,9.656251e+06,2.780823e+08,1.434415e+07,1.717444e+08,8.814393e+06,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,NaN,...,2.024740e+07,1.911173e+07,1.833841e+07,1.722713e+07,6.087501e+08,1.170709e+06,5.269042e+08,1.505514e+07,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,NaN,...,1.972566e+07,1.469958e+07,1.758779e+07,6.163408e+06,2.295846e+08,3.956300e+05,4.106926e+08,4.215763e+06,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,NaN,...,2.138812e+07,1.514664e+07,1.399465e+07,1.097942e+06,7.995382e+08,1.084972e+07,7.490399e+08,1.279728e+07,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,NaN,...,1.525938e+07,1.896287e+07,1.712458e+07,4.152180e+05,5.277072e+08,3.529801e+06,5.507095e+08,1.391032e+07,38542814.0,569138589.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149996,7.277826e+18,4/29/2019 7:28,451.0,4/30/2019 6:02,214.0,81230.0,2.082022e+14,3.365069e+10,3.548311e+13,NaN,...,1.619167e+07,1.176343e+07,1.788370e+07,1.967816e+07,5.266097e+08,9.197207e+06,3.264510e+06,1.348742e+07,57628851.0,574175259.0
149997,7.349883e+18,4/29/2019 7:28,483.0,4/30/2019 10:41,187.0,97970.0,2.082019e+14,3.366345e+10,3.566051e+13,NaN,...,1.387723e+07,8.288284e+06,1.935015e+07,2.129315e+07,6.268931e+08,4.735033e+06,7.121804e+08,2.457758e+06,39135081.0,666648844.0
149998,1.311448e+19,4/29/2019 7:28,283.0,4/30/2019 10:46,810.0,98249.0,2.082017e+14,3.362189e+10,3.572121e+13,NaN,...,2.266051e+07,1.855903e+06,9.963942e+06,5.065760e+06,5.535395e+08,1.339432e+07,1.211009e+08,1.131473e+07,34912224.0,592786405.0
149999,1.311448e+19,4/29/2019 7:28,696.0,4/30/2019 10:40,327.0,97910.0,2.082021e+14,3.361962e+10,8.618620e+13,NaN,...,8.817106e+06,8.305402e+06,3.322253e+06,1.317259e+07,3.525370e+08,2.529475e+06,8.147131e+08,1.406930e+06,29626096.0,371895920.0
150000,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,...,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,NaN,NaN

In [10]:
res.basic_info1()

Warning: The following columns were not found and will not be dropped: ['Avg RTT UL (ms)', '17  Nb of sec with 31250B < Vol DL < 125000B', '18  Nb of sec with 37500B < Vol UL', 'Last Location Name', 'HTTP DL (Bytes)', '250 Kbps < DL TP < 1 Mbps (%)', '15  Nb of sec with 125000B < Vol DL', 'UL TP > 300 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)', 'Avg RTT DL (ms)', 'Avg Bearer TP DL (kbps)', 'UL TP < 10 Kbps (%)', 'TCP UL Retrans. Vol (Bytes)', '16  Nb of sec with 1250B < Vol UL < 6250B', 'DL TP > 1 Mbps (%)', 'TCP DL Retrans. Vol (Bytes)', '10 Kbps < UL TP < 50 Kbps (%)', 'DL TP < 50 Kbps (%)', '50 Kbps < UL TP < 300 Kbps (%)', 'Avg Bearer TP UL (kbps)']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 39 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   HTTP UL (Bytes)                           68191 non-null   float64
 10  Activity Duration DL (ms)                 150000 non-null  float64
 11  Activity Duration UL (ms)                 150000 non-null  float64
 12  Dur. (ms).1                               150000 non-null  float64
 13  Handset Manufacturer                      149429 non-null  object
 14  Handset Type                              149429 non-null  object
 15  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 16  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 17  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 18  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 19  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 20  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 21  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 22  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 23  Social Media DL (Bytes)                   150001 non-null  float64
 24  Social Media UL (Bytes)                   150001 non-null  float64
 25  Google DL (Bytes)                         150001 non-null  float64
 26  Google UL (Bytes)                         150001 non-null  float64
 27  Email DL (Bytes)                          150001 non-null  float64
 28  Email UL (Bytes)                          150001 non-null  float64
 29  Youtube DL (Bytes)                        150001 non-null  float64
 30  Youtube UL (Bytes)                        150001 non-null  float64
 31  Netflix DL (Bytes)                        150001 non-null  float64
 32  Netflix UL (Bytes)                        150001 non-null  float64
 33  Gaming DL (Bytes)                         150001 non-null  float64
 34  Gaming UL (Bytes)                         150001 non-null  float64
 35  Other DL (Bytes)                          150001 non-null  float64
 36  Other UL (Bytes)                          150001 non-null  float64
 37  Total UL (Bytes)                          150000 non-null  float64
 38  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(35), object(4)
memory usage: 44.6+ MB